name: 01-CLA-Assistant
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize,reopened]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: read # this can be 'read' if the signatures are in remote repository
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: ${{ contains(github.event.comment.body, 'I have read the CLA Document and I hereby sign the CLA') }} || github.event_name == 'pull_request_target'
        uses: SiliconLabsSoftware/action-cla-assistant@silabs_flavour_v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "cla_signatures_db.json"
          path-to-document: "https://github.com/SiliconLabsSoftware/bluetooth-AoA-example/blob/main/cla.md"
          # branch should not be protected
          branch: 'cla-database'
          allowlist: silabs-*,bot*
          # the following are the optional inputs - If the optional inputs are not given, then default values will be taken
          remote-organization-name: "SiliconLabsInternal"
          remote-repository-name: "contributor-license-agreements"
          create-file-commit-message: "Created the CLA database file. CLA Assistant Lite bot created this file."
          signed-commit-message: "$contributorName has signed the CLA in $owner/$repo#$pullRequestNo"
